### ISSUE TITLE
What is the purpose of this user that is inserted into the database?

### ISSUE THREAD

**Issue by mjbrennan99** [ShinobiCCTV/Shinobi#11]
What is the purpose of this user inserted into the db?  Is it part of the CE vs Pro?

https://github.com/ShinobiCCTV/Shinobi/blob/3bbdba721777421c31bc457632ad8443463304ac/sql/default_data.sql#L15

**Comment by moeiscool** [comment]
it is a demonstration user, you don't have to add it. You can go to the Superuser panel and create a fresh one if you want. It's just to make it easier to grasp how Shinobi works. It's in both.

Differences of Shinobi CE and Shinobi Pro
http://shinobi.video/articles/2017-08-03-shinobi-ce-and-shinobi-pro

Differences between account types.
http://shinobi.video/articles/2017-08-15-difference-between-superuser-admin-and-subaccount

Also please ask general questions in the Discord community chat. The issues section is only for logging bugs with the software. Thanks!
