### ISSUE TITLE
Editing monitor, Mode changes to Disabled

### ISSUE THREAD

**Issue by Soljia** [ShinobiCCTV/Shinobi#13]
I'm trying to get more information now, but editing a monitor that is already recording (or watching) causes it to go to Disabled. Now, you have to click save for it to actually take effect. I'm thinking the JSON passed is incorrect.

**Comment by Soljia** [comment]
Alright, I'm not sure what the purpose of this section is. However, in main.dash2.js, under case'edit', I can see you get e.values=$.ccio.mon[e.mid]; if $.ccio.mon[e.mid] is initialized/not null. However, down lower, you have a section with if(e.openTabs[e.mid]) that causes some values to be overwritten. I added '&& !e.values' to this, and it seems to fix the problem. Again, I'm not sure what the function of this if statement is.

          ```
  }else{
                e.p.find('.am_notice_edit').show()
                //edit monitor
                e.p.find('[monitor="delete"]').show()
                e.mt.find('span').text('<%-cleanLang(lang.Edit)%>');
                e.mt.find('i').attr('class','fa fa-wrench');
                e.values=$.ccio.mon[e.mid];
                console.log('Getting monitor data');
                console.log(e.values);
            }
            $.aM.selected=e.mid;
            e.openTabs=$.ccio.op().tabsOpen
            if(e.openTabs[e.mid] && !e.values){
                e.values=e.openTabs[e.mid]
            }
                console.log('Passing import data');
                console.log(e);
            $.aM.import(e)

```

**Comment by moeiscool** [comment]
It's not a bug.. it's just a really annoying function i need to clean up. It is saving your changes before you hit save in the browser localStorage. You can click the "Not Saved" button in the bottom left and remove it from the list by clicking the trash can icon next to the said monitor name/id.
