### ISSUE TITLE
Not able to login with docker

### ISSUE THREAD

**Issue by zoell** [ShinobiCCTV/Shinobi#19]
I downloaded the master and started like this (I did not do anything else):

docker-compose up

And when I opened the web page on port 8080, I tried to use the email ccio@m03.ca and password as a password and the login page just realoads, I cannot login.

The first start has some DB connection issues before the db actually starts up but after that it is ok.

Second start:

```
u1@srv1:~/shinobi$ sudo docker-compose up
Starting shinobi_db_1 ...
Starting shinobi_db_1 ... done
Starting shinobi_motion_1 ...
Starting shinobi_cron_1 ...
Starting shinobi_motion_1
Starting shinobi_cron_1
Starting shinobi_camera_1 ...
Starting shinobi_camera_1 ... done
Attaching to shinobi_db_1, shinobi_cron_1, shinobi_motion_1, shinobi_camera_1
db_1      | 2017-10-01 14:51:39 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1      | 2017-10-01 14:51:39 0 [Note] mysqld (mysqld 5.6.37) starting as process 1 ...
cron_1    | Shinobi : cron.js started
camera_1  | NODE.JS version : v8.6.0
camera_1  |
camera_1  | FFMPEG version : 3.2.6
camera_1  | Shinobi - PORT : 8080
camera_1  | 2017-10-01T14:51:45+00:00 Already applied critical update.
```

Is there anything wrong with this?

**Comment by moeiscool** [comment]
Sorry. Frankly I'm not sure as docker is not supported. Please find someone in the community chat who may know something about this http://discordapp.com/invite/mdhmvuH/

**Comment by viktorsmari** [comment]
If you go to `localhost:8080/super` and login with:

Username : ccio@m03.ca
Password : password

you can and  create your own login.
