### ISSUE TITLE
UX: Allow closing of modal boxes with Escape keyboard button

### ISSUE THREAD

**Issue by viktorsmari** [ShinobiCCTV/Shinobi#38]
Right now you always have to click the X in the top right corner.
Also, making this X bigger would help

![2017-12-14_761x150](https://user-images.githubusercontent.com/1689020/34003106-b6765d48-e0f4-11e7-9edc-9d15fddb7f36.png)

**Comment by moeiscool** [comment]
click on the backdrop, it should also close it. This was mentioned before but the attribute that allowed that needed to be removed, i forgot why.

For future bug reports please post on the forum.

**Comment by viktorsmari** [comment]
The reddit forum?

**Comment by moeiscool** [comment]
Here https://forum.shinobi.video/. The reddit is no longer the main forum, sorry if its confusing.
