### ISSUE TITLE
behind reverse proxy

### ISSUE THREAD

**Issue by scipioni** [ShinobiCCTV/Shinobi#39]
It would be nice adding a conf.json param to add some base_url to permit to access shinobi behind reverse proxy with subpaths (/somepath instead of '/')

For example https://example.com/myshinoby/  -> reverse proxy -> http://internal.ip:8080/

conf.json
```
port: 8080,
base_url: "/myshinobi",
...
```

**Comment by moeiscool** [comment]
Please post suggestions in the forum. I have manually made the post for you this time. Thanks!

https://forum.shinobi.video/topic/107/add-configurable-path-for-relative-url-behind-reverse-proxy
