### ISSUE TITLE
Parsed PTZ Control URL contains double port

### ISSUE THREAD

**Issue by mcarver** [ShinobiCCTV/Shinobi#7]
`d.URLobject.host` should be `d.URLobject.hostname` in this location because when URL options are built for HTTP GET, the port is included 2 times:

https://github.com/ShinobiCCTV/Shinobi/blob/ce372e3b0555dc336dc49f19e4cc13a271c2fa07/camera.js#L1915

Example:
`node -p "var URL=require('url'); URL.parse('http://192.168.1.1:88');"`

Result:
 ```
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '192.168.1.1:88',     <-- Port is here
  port: '88',     <--Port is also here
  hostname: '192.168.1.1',     <--Should use this value for d.options.host
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://192.168.1.1:88/' }
```

Thanks!

**Comment by moeiscool** [comment]
thanks! this change will be in the next commit :D
